import { describe, expect, it, vi } from 'vitest';
import { DomainError, ExceptionControlService, Roles, Statuses } from '../domain.mjs';

const actor = (role) => ({ id: `${role}-user`, role });
const input = { supplier: 'Northstar Plastics', subjectId: 'delegate-11', requestedScope: 'Temporary audit vault review', businessJustification: 'Remediation evidence review' };
const createService = () => { const persist = vi.fn(async () => {}); return { persist, service: new ExceptionControlService({ persist, now: () => '2026-08-24T00:00:00.000Z' }) }; };
describe('ExceptionControlService', () => {
  it('moves an exception through assessment, authorization, mitigation, and closure', async () => { const { service, persist } = createService(); const item = await service.submit(actor(Roles.REQUESTER), input); await service.assess(item.id, actor(Roles.ANALYST), { assessmentReference: 'RSK-11' }); await service.authorize(item.id, actor(Roles.AUTHORITY), { expiryDate: '2026-09-30' }); await service.mitigate(item.id, actor(Roles.OWNER), { controlReference: 'CTRL-11' }); const closed = await service.close(item.id, actor(Roles.ASSURANCE), { closureDecision: 'effective' }); expect(closed.status).toBe(Statuses.CLOSED); expect(closed.audit).toHaveLength(5); expect(persist).toHaveBeenCalledTimes(5); });
  it('blocks non-requesters from submitting exceptions', async () => { const { service } = createService(); await expect(service.submit(actor(Roles.ANALYST), input)).rejects.toMatchObject({ code: 'FORBIDDEN' }); });
  it('requires assessment before authorization', async () => { const { service } = createService(); const item = await service.submit(actor(Roles.REQUESTER), input); await expect(service.authorize(item.id, actor(Roles.AUTHORITY), { expiryDate: '2026-09-30' })).rejects.toMatchObject({ code: 'INVALID_STATE' }); });
  it('requires authority role for authorization', async () => { const { service } = createService(); const item = await service.submit(actor(Roles.REQUESTER), input); await service.assess(item.id, actor(Roles.ANALYST), { assessmentReference: 'RSK-11' }); await expect(service.authorize(item.id, actor(Roles.OWNER), { expiryDate: '2026-09-30' })).rejects.toMatchObject({ code: 'FORBIDDEN' }); });
  it('requires mitigation before assurance closure', async () => { const { service } = createService(); const item = await service.submit(actor(Roles.REQUESTER), input); await service.assess(item.id, actor(Roles.ANALYST), { assessmentReference: 'RSK-11' }); await service.authorize(item.id, actor(Roles.AUTHORITY), { expiryDate: '2026-09-30' }); await expect(service.close(item.id, actor(Roles.ASSURANCE), { closureDecision: 'effective' })).rejects.toMatchObject({ code: 'INVALID_STATE' }); });
  it('retains closed cases in list output', async () => { const { service } = createService(); const item = await service.submit(actor(Roles.REQUESTER), input); await service.assess(item.id, actor(Roles.ANALYST), { assessmentReference: 'RSK-11' }); await service.authorize(item.id, actor(Roles.AUTHORITY), { expiryDate: '2026-09-30' }); await service.mitigate(item.id, actor(Roles.OWNER), { controlReference: 'CTRL-11' }); await service.close(item.id, actor(Roles.ASSURANCE), { closureDecision: 'effective' }); expect(service.list()).toEqual([expect.objectContaining({ id: item.id, status: Statuses.CLOSED })]); });
  it('returns typed errors for absent cases', () => { const { service } = createService(); expect(() => service.get('unknown')).toThrow(DomainError); });
});
